trigger:
  branches:
    include:
      - main

pool:
  name: self-hosted-vm1

variables:
  imageName: flask-app

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    steps:
    - checkout: self

    - task: Docker@2
      inputs:
        command: buildAndPush
        containerRegistry: 'acr-connection'  # replace with actual name
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        tags: |
          v1

- stage: DeployToAKS
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    steps:
    - checkout: self

# Retrieve secrets from Key Vault
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'AzureRM-devops'
        KeyVaultName: 'devopskeyvaultshivam'
        SecretsFilter: '*'  # or 'my-secret-token'
        RunAsPreJob: true
# Deploy to AKS using kubectl apply 
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'AzureRM-devops'  # replace with actual name
        azureResourceGroup: 'devops-rg'
        kubernetesCluster: 'devops-aks'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'flask-deployment.yaml'
