trigger:
  branches:
    include:
      - main

pool:
  name: self-hosted-vm1

variables:
  imageName: flask-app
  imageTag: $(Build.BuildID)
  BuildID: $(Build.BuildID)
  my-secret-token: $(my-secret-token)

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    steps:
    - checkout: self

    - task: Docker@2
      inputs:
        command: buildAndPush
        containerRegistry: 'acr-connection'  # replace with actual name
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        tags: |
          $(imageTag)

- stage: DeployToAKS
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    steps:
    - checkout: self

# Retrieve secrets from Key Vault
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'AzureRM-devops'
        KeyVaultName: 'devopskeyvaultshivam'
        SecretsFilter: '*'  # or 'my-secret-token'
        RunAsPreJob: true

    - task: replacetokens@3
      inputs:
        rootDirectory: '$(System.DefaultWorkingDirectory)'
        targetFiles: '**/flask-deployment.yaml'
        encoding: 'utf-8'
        tokenPrefix: '__'
        tokenSuffix: '__'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        enableTelemetry: false 

# Deploy to AKS using kubectl apply 
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'AzureRM-devops'  # replace with actual name
        azureResourceGroup: 'devops-rg'
        kubernetesCluster: 'devops-aks'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'flask-deployment.yaml'
