apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: shivamadevopscr.azurecr.io/flask-app:$(Build.BuildID)
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_TOKEN
          value: "$(my-secret-token)"  # pulled from Azure Key Vault via pipeline 
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
